# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    platform: linux/x86_64
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_HOST: '%'
